version: "3.8"

services:
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nodejs
    env_file:
      - ./frontend/.env

  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
      - "10000-10100:10000-10100/udp"
      - "10000-10100:10000-10100/tcp" # RTP ports
    env_file:
      - ./server/.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
    depends_on:
      - nextjs
      - nodejs

volumes:
  postgres_data:
