version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: expresso_db
      POSTGRES_USER: expresso_user
      POSTGRES_PASSWORD: password
    volumes:
      - expresso_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expresso_user -d expresso_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Django Channels and caching
  redis:
    image: redis:7-alpine
    volumes:
      - expresso_redis_data:/data
    ports:
      - "6380:6379" # Map host port 6380 to container port 6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nodejs
    env_file:
      - ./frontend/.env

  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    env_file:
      - ./server/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - nextjs
      - nodejs
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  expresso_postgres_data:
    driver: local
  expresso_redis_data:
    driver: local
