version: "1.1"

services:
  api:
    build: .
    platform: linux/amd64
    command: bash -c "python manage.py makemigrations api messagesio users videocall && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: expresso-backend
    env_file: ".env"
    volumes:
      - .:/expresso:rw
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - DATABASE_URL
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT

  nginx:
    image: nginx:alpine
    platform: linux/amd64
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - public_assets:/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl

  # Only for localhost
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

volumes:
  public_assets:
