version: "1.1"

services:
  api:
    build: .
    image: 471112891073.dkr.ecr.eu-north-1.amazonaws.com/expresso-backend:latest
    platform: linux/amd64
    command: bash -c "python manage.py makemigrations api messagesio users videocall && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: expresso-backend
    volumes:
      - .:/expresso:rw
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    platform: linux/amd64
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - public_assets:/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl

volumes:
  public_assets:
