name: expresso-backend
services:
  # PostgreSQL Database
  expresso-postgres:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: expresso-postgres
    environment:
      POSTGRES_DB: expresso_db
      POSTGRES_USER: expresso_user
      POSTGRES_PASSWORD: password
    volumes:
      - expresso_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expresso_user -d expresso_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - expresso_backend_network

  expresso-api:
    build: .
    platform: linux/amd64
    container_name: expresso-backend
    command: bash -c "sleep 10 && python manage.py makemigrations api messagesio users videocall && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:4000"
    env_file: ".env"
    volumes:
      - .:/expresso:rw
      - ./staticfiles:/backend/staticfiles:rw
    ports:
      - "4002:4000"
    environment:
      - DATABASE_URL=postgresql://expresso_user:password@expresso-postgres:5432/expresso_db
      - POSTGRES_DB=expresso_db
      - POSTGRES_USER=expresso_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=expresso-postgres
      - POSTGRES_PORT=5432
    depends_on:
      expresso-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - expresso_backend_network

volumes:
  expresso_postgres_data:
    driver: local
    name: expresso_postgres_data

networks:
  expresso_backend_network:
    driver: bridge
    name: expresso_backend_network
