services:
  expresso-mediasoup-server:
    build: .
    ports:
      - "4003:4444"
      - "10000-10100:10000-10100/udp"
      - "10000-10100:10000-10100/tcp" # RTP ports
    env_file:
      - ./.env
    restart: unless-stopped