services:
  expresso-mediasoup-server:
    build: .
    container_name: expresso-mediasoup-server
    ports:
      - "4003:4444"
      - "10000-10100:10000-10100/udp"
      - "10000-10100:10000-10100/tcp" # RTP ports
    env_file:
      - ./.env
    restart: unless-stopped
    privileged: true # Required for io_uring
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    networks:
      - expresso_sfu_network

networks:
  expresso_sfu_network:
    driver: bridge
    name: expresso_sfu_network
