version: "1.1"
services:
  mediasoup-server:
    build: .
    ports:
      - "4444:4444"
      - "10000-10100:10000-10100/udp"
      - "10000-10100:10000-10100/tcp" # RTP ports
    env_file:
      - ./.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - mediasoup-server
